spring:
  data:
    mongodb:
      uri: mongodb://yuxiang:8798132543@139.199.29.250:27017/flowpp
  servlet:
    multipart:
        enabled: true
        max-file-size: 20MB
        max-request-size: 200MB
server:
  port: 8001
